language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
addons:
  apt:
    packages:
    - expect
    - rpm
    - gnupg
after_success:
- mkdir $HOME/.gnupg
- openssl aes-256-cbc -K $encrypted_168997f84686_key -iv $encrypted_168997f84686_iv
  -in gpg.tar.enc -out gpg.tar -d
- tar xv -C $HOME/.gnupg -f gpg.tar
- GPG_PATH=$HOME/.gnupg ./travis-sign-rpm.sh
deploy:
  provider: releases
  api_key:
    secure: E5dKfiXBUTFpIJFWSk2+jBcS6FdO++DHqqGp8XDtrrCpKJfynYqPR+/23oYKYVz+H21CnEiUTqtVKvlftccWbErcRAD3R0G1bw6efj3TNiBb0Z0dRa8qgP+3NVTWhRZ4hwSn/0mClY96kz3cEjiJlBs6lYgneKlmg2As++LDjGIWZEfPUBXK6gtG69ZtMj2NBibKg1KQWZV6nZApBvYtkGJJqhu82jlDMbi5ltaOayVl4ISy0NlfcyW9ZNeLsCgjq9NVl5UV7ti6wB25fosz3fc7OZVF0SlU7Txg5Gi0bsnvRAijZRpZQwuo0Dza3Tqv6YDTXmfZT8qaqF6+SGNBH1BLSVApk2pBddJATzM5o0SZkuywUK4tMq6qCJjdPgMXnR4b/t3jK5f5w/ahWgYsqU7z7dBpxDDWafDFibkylJEQaUexktYdxq7JQZ5F6CNcT+qkPhj6LELR9eYh22xnuorwh6sfBfQqWJ0zveD9IcAv4Fl0ogXniftaLxRJ+G9vSQtzruWCTQRT3Ys2eIjc67wI47uMFcU5naM/YDt9BAQZzBoP9vKGiiyRwoa5kqpEy++qtod8oQTN1mw0B3BubrtlDAKirp8S+Zoix7EAvBt0abIO+zOvblUAjzb4zf2DxXkakvWZ4hxq8LnOItxItyBBRbDxiNYigYd8lRW0los=
  file:
  - build/distributions/rd-*.zip
  - build/distributions/rd-*.tar
  - build/distributions/rundeck-cli*.rpm
  - build/distributions/rundeck-cli*.deb
  - build/libs/rundeck-cli-*-all.jar
  on:
    repo: rundeck/rundeck-cli
    tags: true
  file_glob: true
after_deploy:
- ./gradlew -PbintrayUser=gschueler -PbintrayUserOrg=rundeck -PbintrayRepo=rundeck-rpm bintrayUpload
- ./gradlew -PbintrayUser=gschueler -PbintrayUserOrg=rundeck -PbintrayRepo=rundeck-deb -PdebUpload=true bintrayUpload
env:
  global:
  - secure: 2LDWRCZsuUYNUNHQz4oiaq9VIcdp0ziI7SKBxUxfqT4rehJ0J7kz+UPqwtgxMiUyQaHJQqzkcR+m6H3VZj9BREY+POiyu+yJOqhe3KRpDAfiN/gnwN81Nh9wloVaxyVe6i5yPaaBvE5vIREi7SAUdDtdsQ6WSkQ3JnaSL5Nz6e3DKR6+wgaTmBhh/TTW1YuN1qo5EjBpm0//M+KwY5BvVYOfPYLHCpVqnWFePQBkZY13lvufC5XPipXMf6c5Un/Uy6oVaRgLSPHDyELQvBzMSRPtzNmJSDm75LvclHHgDYEUcrcxRoWgAEISaBeIpGhe/PnsswCtQMfQBIm0W8Cv+HThbdCrrTdz/hWsohVvLFkCl9L8NOTOnATr2I9F0GBmsdhJvvr10JqGGol8Y9wwu5eiO9AWmchjZPicIWj5Dwo9E8AdT20aX4l287StESedS/Wtqh7gdf4d3Y1svWLEmh3gbERqOI9hRDV0DotfumhaW49SbaN/XecODiyPrnLBONSrYk1bWADDAvBZm/Jy0hvFbaVFFI8HfZMVJCO4GJJwna2MEMnsouNl2eDBFtvX5JHQ00JP4QacPFwW3/0NsgdaUGLiPSNezNJ1kBYtVbhQg4oL3yTkFaU6KuGhJcdSCVJUwOeP0YZF0oklofLhEhc4puzAi6EmGvLpMeh/huw=
  - secure: "uWOoB6aY4wVByhGvLespKyHO+wGM2byeI/TTe2cphsEgUIasgfDFuNC/l8Ta+qVaAjHY0jm/4zmWUWB50oO/46iFTywWD0PYH256EPaQ7eSEXPXZbY1q9KNlGoVviaqFBwkjWhLcsPgyoi9ejVltkLnT+J0Pk+VIN8bTFaqRo9VyHpv3lCXIdksIX3RBc/C4s9bUyHYODKuvh+t6e4b+cjuXqzJGC1CNdwswZ1WUW9SsTWFlzxUKxkar5hDd9vuMSTLg7VmtnARRVyLI+OD6CYH4+oK8R4mCMCJZCDBxt3M4aaQFPFlkRCpdrZrMPWxlOADtfYziyjyPTk3EzKHhlkNaHPOCggOBFnx6OrzOIBv7XDIoPlldBMUyNWEAiTRQ1HEkcGk/ebe1bK1iqtwvU7MQWuJB0ywZ4WceUUHA49rUbxHzzWrUD7ghAe9nf2dspAXTPTXWsr5gcga1+LwBl/xvE/+F7iYY3lepgByhvjPUYGMM1JSe2DQL3M4OLYS65nkzRWsb+6E3RE7Sz8aXuPdaqop+Tdzelj5xFu17kpZOITInIMFabSZc5jWY+xujl5YVQY0DtKfTODqXNDptEq9S4iHnKioXV9qfTZ0AOmtyp45bVXYlUAOiEjN2jsjfs0w6fVFnGtBPOi4E8K0ZDchkE/WboWWCAq2L/m9mFbo="
  - secure: "7+XXFQdjfAQ/uo+GVM3nElg6bzevXTQADL6rk1VAOH9+DpNM/TGSn248XG8rmjPA1MLU4Rb+O+9lAIAwe4YSKPWo/xzXyw1xMC2005UrfV+RDWwGZPhkN+/hzXIH5vaC6T5E6Mvg5fCny3/xCQNWRdeeN5toZxZDPdkBAyF1OwqE7DYP531sI5tg/TSP3vefsRCEz6tpUdD+sAFfJuI+tI1jBPaDGCsVFysDbfp5zmTWfn0eH70jUyfVSg9gioHT8T+yDMydxItNij91cPoWHcpCZItezu6zVsO1c0EKNGzGW8DT+2TAJv5iVC2k4EL+h6RwuvGIC9XbYNeTTb9yFshJqNOSffhYQ6p99yyElDYY78n+iZnRfEsAftOtniZ3NzGiS6VGMc0XSYSTmNY8PNlIZbfgdfseXfPX/a8Osz+4qMAIXWEbGMU4OMBAejMlVu9BZYBsgqXw4FzzWLmbWXQ2ovksNmxdohffy8QS6yPV6ceyVsF7WXkaeIand0NU6htDrkPZOuk2owSniZxFFFCUwm4o81B2nMf70y7Z9jjk9vmJ5zorWLsNWTnIkB8fJNkEgL/sEwaqz3g5ZYPGUAXVn5cTrY+QUaHPMqNTrftFSd7jarjf944zBZnYzFaE1gDoDGHWyaluqaIqf7f+X1zs+3mxGHKGiDrqp7A02ow="
